_BASE_: ../Base-MGN.yml

MODEL:
  BACKBONE:
    WITH_IBN: True

DATASETS:
  NAMES: ("Market1501","CUHK01","CUHK02","CUHK03","PKU","MARS","DukeMTMC","MSMT17")
  TESTS: ("Market1501","CUHK01","CUHK02","CUHK03","PKU","MARS","DukeMTMC","MSMT17","PartialREID","OccludedREID","PartialiLIDS")

SOLVER:
  AMP:
    ENABLED: True
  OPT: Adam
  MAX_EPOCH: 80
  BASE_LR: 0.0007
  WEIGHT_DECAY: 0.0005
  IMS_PER_BATCH: 128

  SCHED: CosineAnnealingLR
  DELAY_EPOCHS: 30
  ETA_MIN_LR: 0.0000007

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  FREEZE_ITERS: 1000

  CHECKPOINT_PERIOD: 20

OUTPUT_DIR: logs/mgn_R50-ibn_8data_fullbody_batch128