_BASE_: ../Base-bagtricks.yml

DATASETS:
  # NAMES: ("MSMT17",)
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)
  COMBINEALL: False

SOLVER:  
  MAX_EPOCH: 150
  IMS_PER_BATCH: 64 # 128
  CHECKPOINT_PERIOD: 10

TEST:
  IMS_PER_BATCH: 64 # 128
  RERANK:
    ENABLED: False

MODEL:
  BACKBONE:
    PRETRAIN_PATH: '/home/tuantran/.cache/torch/hub/checkpoints/RepVGG-B3g4-200epochs-train.pth'

OUTPUT_DIR: logs/market1501/regvgg_3
