_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
  
DATASETS:
  NAMES: ("Market1501","CUHK01","CUHK02","CUHK03","PKU","MARS","DukeMTMC","MSMT17")
  # TESTS: ("Market1501","CUHK01","CUHK02","CUHK03","PKU","MARS","DukeMTMC","MSMT17","PartialREID","OccludedREID","PartialiLIDS")
  # TESTS: ("PartialREID","OccludedREID","PartialiLIDS")


INPUT:
  AFFINE:
    ENABLED: false
  AUGMIX:
    ENABLED: true
    PROB: 0.0
  CJ:
    BRIGHTNESS: 0.15
    CONTRAST: 0.15
    ENABLED: false
    HUE: 0.1
    PROB: 0.5
    SATURATION: 0.1
  RPT:
    ENABLED: true
    PROB: 0.5

SOLVER:  
  MAX_EPOCH: 60
  IMS_PER_BATCH: 128
  CHECKPOINT_PERIOD: 5

TEST:
  IMS_PER_BATCH: 128
  RERANK:
    ENABLED: False

OUTPUT_DIR: logs/ma_cu1_2_3_pku_mars_duk_msmt_ep60_batch128_agumix_rpt