_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
  WEIGHTS: /home/thangnv/fast-reid/logs/ma_cu1_2_3_pku_mars_duk_msmt_ep60_batch256/model_final.pth
DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/sbs_S50